# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Set {{ test_profile }} test profile name variable
  set_fact:
    test_profile_name: "{{ (test_profile | list | first if test_profile is not string else test_profile) | trim }}"
- name: Start {{ test_profile_name }} monitoring
  shell:
    cmd: >-
      phoronix-test-suite batch-benchmark {{ test_profile_name }}
  async: 9999999
  poll: 0
- name: Run needed custom task for {{ test_profile_name }}
  include_tasks: "{{ test_profile_name }}.yaml"
