# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Start {{ test_profile_name }} monitoring
  shell:
    cmd: >-
      MONITOR=all phoronix-test-suite batch-benchmark "{{ test_profile_name }}"
  async: 9999999
  poll: 0
