# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Wait for network_monitoring to start
  wait_for:
    path: /tmp/network_mon.log
    state: present
    timeout: 300
