# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Wait for process_monitoring to start
  wait_for:
    path: /tmp/log
    state: present
    timeout: 300
- name: Wait for process_monitoring to record
  command: stat --format=%s /tmp/log
  register: file_size
  until: file_size.stdout | int > 0
  retries: 30
  delay: 10
