---
- name: Generate test results PDF
  shell:
    cmd: >-
      phoronix-test-suite result-file-to-pdf {{ benchmark_item['benchmark_test_run_id'] }}
- name: Fetch PDF result file
  fetch:
    flat: true
    src: /root/{{ benchmark_item['benchmark_test_run_id'] }}.pdf
    dest: ../tests_results/{{ansible_hostname}}_{{ benchmark_item['benchmark_test_run_id'] }}_results.pdf
