# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Set test profile variable
  set_fact:
    test_profile: "{{ (test_profile_name | list | first if test_profile_name is not string else test_profile_name) | trim }}"

- name: Check {{ test_profile }} benchmark previous failed installation
  stat:
    path: /var/lib/phoronix-test-suite/installed-tests/local/{{ test_profile }}/install-failed.log
  register: previous_install_failed
- name: Clean installation directory
  file:
    state: absent
    path: /var/lib/phoronix-test-suite/installed-tests/local/{{ test_profile }}/install-failed.log
  when: previous_install_failed.stat.exists
- name: Copy {{ test_profile }} test profile
  copy:
    src: "{{ test_profile }}"
    dest: /var/lib/phoronix-test-suite/test-profiles/local/
- name: create {{ test_profile }} template
  template:
    src: "{{ item }}"
    dest: "/var/lib/phoronix-test-suite/test-profiles/local/{{ test_profile }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - ../templates/{{ test_profile }}/*.j2

- name: Install {{ test_profile }} benchmark
  shell:
    cmd: >-
      phoronix-test-suite batch-install {{ test_profile }}
- name: Check {{ test_profile }} benchmark installation
  stat:
    path: /var/lib/phoronix-test-suite/installed-tests/local/{{ test_profile }}/install-failed.log
  register: install_failed
- name: Fail if {{ test_profile }} benchmark installation failed
  fail:
    msg: "{{ test_profile }} benchmark installation did not succeed. Check full error in {{ install_failed.stat.path }}"
  when: install_failed.stat.exists
