# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Run needed custom task for {{ monitoring_item['name'] }}
  include_tasks: "{{ monitoring_item['name'] }}.yaml"
