# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Wait for network_monitoring to finish
  async_status:
    jid: "{{ monitoring_item.status.ansible_job_id }}"
  register: temp
  until: temp.finished
  retries: 10000
  delay: 10
- name: Generate test results PDF
  shell:
    cmd: >-
      phoronix-test-suite result-file-to-pdf {{ monitoring_item['monitoring_test_run_id'] }}
- name: Fetch PDF result file
  fetch:
    flat: true
    src: /root/{{  monitoring_item['monitoring_test_run_id'] }}.pdf
    dest: ../tests_results/{{ansible_hostname}}_{{  monitoring_item['monitoring_test_run_id'] }}_results.pdf
