# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Initialize variable roles
  set_fact:
    active_benchmark: "{{ active_benchmark | default([]) }}"
- name: Set test profile variable
  set_fact:
    test_profile_name: "{{ (test_profile | list | first if test_profile is not string else test_profile) | trim }}"
- name: Set test-profile run identifier
  set_fact:
    test_run_id: "{{ test_profile_name | replace('_', '') }}-{{ test_start_time.stdout }}"
- name: Set test-profile arguments
  set_fact:
    test_profile_args: "{{ test_profile_args | default({}) | combine({ item.key: item.value }) }}"
  with_dict: "{{ lookup('vars', test_profile_name) }}"
  when: test_profile_name is defined and test_profile_name in vars
- name: Run {{ test_profile_name }} benchmark
  shell:
    cmd: >-
      TEST_RESULTS_NAME="{{ benchmark_test_run_id }}" phoronix-test-suite batch-benchmark "{{ test_profile_name }}"
  environment: "{{ test_profile_args if test_profile_args is defined else {} }}"
  async: 9999999
  poll: 0
  register: temp_status
- name: Register test profile benchmark status
  set_fact:
    active_benchmark: "{{ active_benchmark + [ { 'name': test_profile_name, 'status': temp_status } ] }}"
- name: Generate {{ test_profile_name }} test results PDF
  shell:
    cmd: >-
      phoronix-test-suite result-file-to-pdf {{ test_run_id }}
- name: Fetch {{ test_profile_name }} PDF result file
  fetch:
    flat: true
    src: /root/{{ test_run_id }}.pdf
    dest: ../tests_results/{{ansible_hostname}}_{{ test_run_id }}_results.pdf
