# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Prepare hypervisor and VMs
  become: true
  hosts:
    - hypervisors
    - VMs
  tasks:
    - name: Copy phoronix configuration file
      copy:
        src: ../files/configuration/phoronix-test-suite.xml
        dest: /etc/phoronix-test-suite.xml
    - name: Copy top configuration file
      copy:
        src: ../files/configuration/topdefaultrc
        dest: /etc/topdefaultrc
    - name: Copy pie chart generation script
      copy:
        src: ../files/generate_pie_chart.sh
        dest: /usr/bin/generate_pie_chart
        mode: '0777'
    - name: Configure monitoring test-profiles
      include_role:
        name: "configure_test_profiles"
      vars:
        test_profile_name: "{{ item }}"
      loop: "{{ monitoring }}"
      when: monitoring is defined
    - name: Configure benchmark test-profiles
      include_role:
        name: "configure_test_profiles"
      vars:
        test_profile_name: "{{ item }}"
      loop: "{{ benchmark }}"
      when: benchmark is defined
