# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Prepare hypervisor and VMs
  become: true
  hosts:
    - monitored_machines
    - benchmarked_machines
  tasks:
    - name: Include dependencies variables
      include_vars:
        file: "dependencies.yaml"
    - name: Include patches variables
      include_vars:
        file: "patches.yaml"
    - name: Include test-profiles variables
      include_vars:
        file: "test_profiles.yaml"
    - name: Check needed dependencies
      command: which {{ item }}
      loop: "{{ dependencies }}"
    - name: Apply needed patches
      patch:
        src: "patches/{{ item.name }}"
        basedir: "{{ item.basedir }}"
        strip: 1
        ignore_whitespace: true
      loop: "{{ patches }}"
      when: patches is defined
    - name: Copy phoronix configuration file
      copy:
        src: ../files/configuration/phoronix-test-suite.xml
        dest: /etc/phoronix-test-suite.xml
    - name: Copy top configuration file
      copy:
        src: ../files/configuration/topdefaultrc
        dest: /etc/topdefaultrc
    - name: Copy pie chart generation script
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0777'
      loop:
      - src: ../files/generate_pie_chart.sh
        dest: /usr/bin/generate_pie_chart
      - src: ../files/generate_pie_chart_xml.awk
        dest: /usr/bin/generate_pie_chart_xml.awk
    - name: Configure monitoring test-profiles
      include_role:
        name: "configure_test_profiles"
      vars:
        test_profile_name: "{{ item }}"
      loop: "{{ test_profiles }}"
