# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Prepare localhost
  hosts:
    localhost
  tasks:
    - name: Create tests results directory
      file:
        path: ../tests_results
        state: directory
- name: Start monitoring on the hypervisors and VMs
  become: true
  hosts:
    - hypervisors
    - VMs
  tasks:
    - name: Run monitoring test-profiles
      include_role:
        name: "run_monitoring_tests_profiles"
      vars:
        test_profile: "{{ item }}"
      loop: "{{ monitoring }}"
      when: monitoring is defined

- name: Start benchmark on the hypervisors and VMs
  become: true
  hosts:
    - hypervisors
    - VMs
  tasks:
    - name: Run test-profiles
      include_role:
        name: "run_benchmark_test_profiles"
      vars:
        test_profile: "{{ item }}"
      loop: "{{ benchmark }}"
      when: benchmark is defined
- name: End monitoring on hypervisors ans VMs
  become: true
  hosts:
    - VMs
    - hypervisors
  tasks:
  - name: Generate monitoring test-profiles results
    include_role:
      name: "get_monitoring_test_results"
    vars:
      test_profile: "{{ item }}"
    loop: "{{ monitoring }}"
    when: monitoring is defined
- name: Execute last tasks on localhost
  hosts:
    localhost
  tasks:
    - name: Rename test results directory
      shell:
        cmd: >-
          mv ../tests_results ../tests_results-$(date +%F_%Hh%Mm%S)
